cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from orders.views import order_create

app_name = 'orders'

urlpatterns = [
    path('', order_create, name='order_create')
]

shop/urls.py
from django.urls import path

from shop.views import *

app_name = 'shop'

urlpatterns = [
    path('home/', home, name='home'),
    path('about/', about, name='about'),
    path('', product_list, name='product_list'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models

from shop.models import Product


class Order(models.Model):
    first_name = models.CharField(max_length=63)
    last_name = models.CharField(max_length=63)
    email = models.EmailField(max_length=255)
    postal_code = models.CharField(max_length=20)
    address = models.CharField(max_length=255)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    details = models.TextField(blank=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="products")
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    image = models.ImageField(upload_to='media/products/%Y/%M/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created'])
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, widget=forms.TextInput(attrs={
        'class': 'form-control text-center',
        'value': 1,
        'max': 20,
        'min': 1,
        'aria-describedby': 'button-addon1',
        'type': 'number'
    }))
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

orders/forms.py
from django import forms

from orders.models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city', 'details']

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST

from cart.cart import Cart
from cart.forms import CartAddProductForm
from shop.models import Product


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    form = CartAddProductForm

    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'override': True})
    return render(request, 'cart/cart.html', {'cart': cart,
                                              'form': form})

orders/views.py
from django.shortcuts import render

from cart.cart import Cart
from orders.forms import OrderCreateForm
from orders.models import OrderItem
from orders.tasks import order_created


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            cart.clear()
            order_created.delay(order.id)
            return render(request, 'orders/thankyou.html', {'order': order})
    else:
        form = OrderCreateForm()
    return render(request, 'orders/checkout.html', {'cart': cart,
                                                    'form': form})

shop/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from cart.forms import CartAddProductForm
from shop.models import Category, Product


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category,
                                     slug=category_slug)
        products = products.filter(category=category)

    paginator = Paginator(products, 6)
    page_number = request.GET.get('page', 1)
    products = paginator.page(page_number)

    return render(request, 'shop/product/shop.html', {'category': category,
                                                      'categories': categories,
                                                      'products': products})


def about(request):
    return render(request, 'shop/about.html')


def product_detail(request, id, slug):
    cart_product_form = CartAddProductForm()

    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    return render(request, 'shop/product/shop-single.html', {'product': product,
                                                             'cart_product_form': cart_product_form})


def home(request):
    return render(request, 'shop/home.html')

cart/templates/cart/cart.html
{% extends 'base.html' %}

{% block main %}
    <div class="site-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-12">
            <div class="site-blocks-table">
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <th class="product-thumbnail">Фотография</th>
                    <th class="product-name">Название</th>
                    <th class="product-price">Цена</th>
                    <th class="product-quantity">Количество</th>
                    <th class="product-total">Итого</th>
                    <th class="product-remove">Удалить</th>
                  </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                {% with product=item.product %}
                  <tr>
                      <td class="product-thumbnail">
                        <img src="{{product.image.url}}" alt="Image" class="img-fluid">
                      </td>
                      <td class="product-name">
                        <h2 class="h5 text-black"><a href="{{ product.get_absolute_url }}">{{product.name|truncatewords:5}}</a></h2>
                      </td>
                      <td>{{item.price}}</td>
                      <td>
                        <form class="mt-1 w-100 d-flex justify-content-center" action="{% url 'cart:cart_add' product.id %}" method="post">
                          <div class="input-group mb-3" style="max-width: 120px;">
                            {% csrf_token %}
                            <p>Максимум: 20</p>
                            <div class="input-group mb-3" style="max-width: 120px;">
                              <div class="input-group-prepend">
                                <button class="btn btn-outline-primary js-btn-minus" type="button">&minus;</button>
                              </div>
                              {{ item.update_quantity_form.quantity }}
                              {{ item.update_quantity_form.override }}
                              <div class="input-group-append">
                                <button class="btn btn-outline-primary js-btn-plus" type="button">&plus;</button>
                              </div>
                            </div>
                            <button class="btn w-100 btn-outline-primary" type="submit">обновить</button>
                          </div>
                        </form>
                      </td>
                      <td>{{item.total_price}}</td>
                      <td>
                        <form action="{% url 'cart:cart_remove' product.id %}" method="POST">
                          {% csrf_token %}
                          <button type="submit" class="btn btn-primary btn-sm">X</button>
                        </form>
                      </td>
                    </tr>
                  {% endwith %}
                {% endfor %}

                </tbody>
              </table>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="row mb-5">
              <div class="col-md-6 mb-3 mb-md-0">
                <a href="{% url 'cart:cart_detail' %}" class="btn btn-primary btn-sm btn-block">Обновить корзину</a>
              </div>
              <div class="col-md-6">
                <a href="{% url 'shop:product_list' %}" class="btn btn-outline-primary btn-sm btn-block">Вернуться в магазин</a>
              </div>
            </div>
<!--            <div class="row">-->
<!--              <div class="col-md-12">-->
<!--                <label class="text-black h4" for="coupon">Coupon</label>-->
<!--                <p>Enter your coupon code if you have one.</p>-->
<!--              </div>-->
<!--              <div class="col-md-8 mb-3 mb-md-0">-->
<!--                <input type="text" class="form-control py-3" id="coupon" placeholder="Coupon Code">-->
<!--              </div>-->
<!--              <div class="col-md-4">-->
<!--                <button class="btn btn-primary btn-sm">Apply Coupon</button>-->
<!--              </div>-->
<!--            </div>-->
          </div>
          <div class="col-md-6 pl-5">
            <div class="row justify-content-end">
              <div class="col-md-7">
                <div class="row">
                  <div class="col-md-12 text-right border-bottom mb-5">
                    <h3 class="text-black h4 text-uppercase">Сумма покупок</h3>
                  </div>
                </div>
                <div class="row mb-5">
                  <div class="col-md-6">
                    <span class="text-black">Итого</span>
                  </div>
                  <div class="col-md-6 text-right">
                    <strong class="text-black">{{cart.get_total_price}} руб.</strong>
                  </div>
                </div>

                {% if form %}
                <div class="row">
                  <div class="col-md-12">
                    <a href="{% url 'orders:order_create' %}" class="btn btn-primary btn-lg py-3 btn-block">Оплатить</a>
                  </div>
                </div>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

orders/templates/orders/checkout.html
{% extends 'base.html' %}

{% block main %}
    <div class="site-section">
      <div class="container">
        <form method="POST" class="row">

          {% csrf_token %}
          {% if form %}
          <div class="col-md-6 mb-5 mb-md-0">
            <h2 class="h3 mb-3 text-black">Детали заказа</h2>
            <div class="p-3 p-lg-5 border">
              <div class="form-group row">
                <div class="col-md-6">
                  <label for="c_fname" class="text-black">Имя <span class="text-danger">*</span></label>
                  <input type="text" class="form-control" id="c_fname" name="first_name">
                </div>
                <div class="col-md-6">
                  <label for="c_lname" class="text-black">Фамилия <span class="text-danger">*</span></label>
                  <input type="text" class="form-control" id="c_lname" name="last_name">
                </div>
              </div>

              <div class="form-group row">
                <div class="col-md-12">
                  <label for="c_address" class="text-black">Адрес <span class="text-danger">*</span></label>
                  <input type="text" class="form-control" id="c_address" name="address" placeholder="Улица Ленина..">
                </div>
              </div>

              <div class="form-group row">
                <div class="col-md-6">
                  <label for="city" class="text-black">Город <span class="text-danger">*</span></label>
                  <input type="text" class="form-control" id="city" name="city">
                </div>
                <div class="col-md-6">
                  <label for="c_postal_zip" class="text-black">Индекс <span class="text-danger">*</span></label>
                  <input type="text" class="form-control" id="c_postal_zip" name="postal_code">
                </div>
              </div>

              <div class="form-group row mb-5">
                <div class="col">
                  <label for="c_email_address" class="text-black">Email <span class="text-danger">*</span></label>
                  <input type="email" class="form-control" id="c_email_address" name="email">
                </div>
              </div>


              <div class="form-group">
                <label for="c_order_notes" class="text-black">Замечание</label>
                <textarea name="details" id="c_order_notes" cols="30" rows="5" class="form-control" placeholder="Write your notes here..."></textarea>
              </div>

            </div>
          </div>
          {% endif %}
          <div class="col-md-6">
            
            <div class="row mb-5">
              <div class="col-md-12">
                <h2 class="h3 mb-3 text-black">Ваш заказ</h2>
                <div class="p-3 p-lg-5 border">
                  <table class="table site-block-order-table mb-5">
                    <thead>
                      <th>Товар</th>
                      <th>Число</th>
                      <th>Цена</th>
                    </thead>
                    <tbody>
                    {% if order == None %}
                    {% for item in cart %}
                    {% with product=item.product %}
                      <tr>
                          <td><a href="{{ product.get_absolute_url }}">{{product|truncatewords:5}}</a></td>
                          <td>{{item.quantity}}</td>
                          <td>{{item.total_price}}</td>
                      </tr>
                    {% endwith %}
                    {% endfor %}
                    {% endif %}

                      <tr>
                        <td class="text-black font-weight-bold"><strong>Итого</strong></td>
                        <td class="text-black font-weight-bold"><strong>{{cart.get_total_price}}</strong></td>
                      </tr>
                    </tbody>
                  </table>

                  <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-lg py-3 btn-block">Оплатить</button>
                  </div>

                </div>
              </div>
            </div>

          </div>
        </form>
        <!-- </form> -->
      </div>
    </div>
{% endblock %}

orders/templates/orders/thankyou.html
{% extends 'base.html' %}

{% block main %}
    <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
            <span class="icon-check_circle display-3 text-success"></span>
            <h2 class="display-3 text-black">Спасибо!</h2>
            <p class="lead mb-5">Ваш заказ успешно создан с id {{order.id}}.</p>
            <p><a href="{% url 'shop:product_list' %}" class="btn btn-sm btn-primary">Назад к покупкам</a></p>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

shop/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Shoppers &mdash; Colorlib e-Commerce Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">


    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

  </head>
  <body>

      <div class="site-wrap">
          {% include 'block/header.html' %}

<!--          <div class="bg-light py-3">-->
<!--              <div class="container">-->
<!--                <div class="row">-->
<!--                  <div class="col-md-12 mb-0"><a href="index.html">Home</a> <span class="mx-2 mb-0">/</span> <strong class="text-black">Shop</strong></div>-->
<!--                </div>-->
<!--              </div>-->
<!--          </div>-->

          {% block main %}
          {% endblock %}

          {% include 'block/footer.html' %}
      </div>

  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>

  <script src="{% static 'js/main.js' %}"></script>

  </body>
</html>

shop/templates/block/header.html
{% load shop_tags %}

<header class="site-navbar" role="banner">
  <div class="site-navbar-top">
    <div class="container">
      <div class="row align-items-center justify-content-around">

        <div class="col-6 col-md-4 order-2 order-md-1 site-search-icon text-left">
          <form action="" class="site-block-top-search">
            <span class="icon icon-search2"></span>
            <input type="text" class="form-control border-0" placeholder="Поиск">
          </form>
        </div>

        <div class="col-12 mb-3 mb-md-0 col-md-4 order-1 order-md-2 text-center">
          <div class="site-logo">
            <a href="{% url 'shop:home' %}" class="js-logo-clone">Naumovets</a>
          </div>
        </div>

        <div class="col-6 col-md-4 order-3 order-md-3 text-right">
          <div class="site-top-icons">
            <ul>
              <li><a href="#"><span class="icon icon-person"></span></a></li>
              <li><a href="#"><span class="icon icon-heart-o"></span></a></li>
              <li>
                <a href="{% url 'cart:cart_detail' %}" class="site-cart">
                  <span class="icon icon-shopping_cart"></span>
                  <span class="count">{{ cart|length }}</span>
                </a>
              </li>
              <li class="d-inline-block d-md-none ml-md-0"><a href="#" class="site-menu-toggle js-menu-toggle"><span class="icon-menu"></span></a></li>
            </ul>
          </div>
        </div>

      </div>
    </div>
  </div>
  <nav class="site-navigation text-right text-md-center" role="navigation">
    <div class="container">
      <ul class="site-menu js-clone-nav d-none d-md-block">
        <li>
          <a href="{% url 'shop:home' %}">Главная</a>
        </li>
        <li>
          <a href="{% url 'shop:about' %}">О нас</a>
        </li>
        <li class="active"><a href="{% url 'shop:product_list' %}">Магазин</a></li>
        <li><a href="#">Каталог</a></li>
        <li><a href="#">Контакты</a></li>
      </ul>
    </div>
  </nav>
</header>

shop/templates/block/pagination.html
{% load shop_tags %}

<div class="row" data-aos="fade-up">
    <div class="col-md-12 text-center">
        <div class="site-block-27">
            <ul>
                {% if page.has_previous %}
                <li><a href="?page={{ page.previous_page_number }}">&lt;</a></li>
                {% endif %}

                {% show_pagination_numbers page %}

                {% if page.has_next %}
                <li><a href="?page={{ page.next_page_number }}">&gt;</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

shop/templates/shop/home.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
<div class="site-blocks-cover" style="background-image: url({% static 'images/hero_1.jpg' %});" data-aos="fade">
  <div class="container">
    <div class="row align-items-start align-items-md-center justify-content-end">
      <div class="col-md-5 text-center text-md-left pt-5 pt-md-0">
        <h1 class="mb-2">Все нужное в нашем магазине</h1>
        <div class="intro-text text-center text-md-left">
          <p class="mb-4">Лучшие цены на товары народного потребления со всех уголков планеты с доставкой по всему СНГ</p>
          <p>
            <a href="{% url 'shop:product_list' %}" class="btn btn-sm btn-primary">За покупками!</a>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="site-section site-section-sm site-blocks-1">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="">
        <div class="icon mr-4 align-self-start">
          <span class="icon-truck"></span>
        </div>
        <div class="text">
          <h2 class="text-uppercase">Бесплатная доставка</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan tincidunt fringilla.</p>
        </div>
      </div>
      <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="100">
        <div class="icon mr-4 align-self-start">
          <span class="icon-refresh2"></span>
        </div>
        <div class="text">
          <h2 class="text-uppercase">Бесплатный возврат</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan tincidunt fringilla.</p>
        </div>
      </div>
      <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="200">
        <div class="icon mr-4 align-self-start">
          <span class="icon-help"></span>
        </div>
        <div class="text">
          <h2 class="text-uppercase">Поддержка 24/7</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan tincidunt fringilla.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="site-section site-blocks-2">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0" data-aos="fade" data-aos-delay="">
        <a class="block-2-item" href="#">
          <figure class="image">
            <img src="{% static 'images/women.jpg' %}" alt="" class="img-fluid">
          </figure>
          <div class="text">
            <span class="text-uppercase">Collections</span>
            <h3>Women</h3>
          </div>
        </a>
      </div>
      <div class="col-sm-6 col-md-6 col-lg-4 mb-5 mb-lg-0" data-aos="fade" data-aos-delay="100">
        <a class="block-2-item" href="#">
          <figure class="image">
            <img src="{% static 'images/children.jpg' %}" alt="" class="img-fluid">
          </figure>
          <div class="text">
            <span class="text-uppercase">Collections</span>
            <h3>Children</h3>
          </div>
        </a>
      </div>
      <div class="col-sm-6 col-md-6 col-lg-4 mb-5 mb-lg-0" data-aos="fade" data-aos-delay="200">
        <a class="block-2-item" href="#">
          <figure class="image">
            <img src="{% static 'images/men.jpg' %}" alt="" class="img-fluid">
          </figure>
          <div class="text">
            <span class="text-uppercase">Collections</span>
            <h3>Men</h3>
          </div>
        </a>
      </div>
    </div>
  </div>
</div>
<div class="site-section block-3 site-blocks-2 bg-light">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-7 site-section-heading text-center pt-4">
        <h2>Featured Products</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="nonloop-block-3 owl-carousel">
          <div class="item">
            <div class="block-4 text-center">
              <figure class="block-4-image">
                <img src="{% static 'images/cloth_1.jpg' %}" alt="Image placeholder" class="img-fluid">
              </figure>
              <div class="block-4-text p-4">
                <h3><a href="#">Tank Top</a></h3>
                <p class="mb-0">Finding perfect t-shirt</p>
                <p class="text-primary font-weight-bold">$50</p>
              </div>
            </div>
          </div>
          <div class="item">
            <div class="block-4 text-center">
              <figure class="block-4-image">
                <img src="{% static 'images/shoe_1.jpg' %}" alt="Image placeholder" class="img-fluid">
              </figure>
              <div class="block-4-text p-4">
                <h3><a href="#">Corater</a></h3>
                <p class="mb-0">Finding perfect products</p>
                <p class="text-primary font-weight-bold">$50</p>
              </div>
            </div>
          </div>
          <div class="item">
            <div class="block-4 text-center">
              <figure class="block-4-image">
                <img src="{% static 'images/cloth_2.jpg' %}" alt="Image placeholder" class="img-fluid">
              </figure>
              <div class="block-4-text p-4">
                <h3><a href="#">Polo Shirt</a></h3>
                <p class="mb-0">Finding perfect products</p>
                <p class="text-primary font-weight-bold">$50</p>
              </div>
            </div>
          </div>
          <div class="item">
            <div class="block-4 text-center">
              <figure class="block-4-image">
                <img src="{% static 'images/cloth_3.jpg' %}" alt="Image placeholder" class="img-fluid">
              </figure>
              <div class="block-4-text p-4">
                <h3><a href="#">T-Shirt Mockup</a></h3>
                <p class="mb-0">Finding perfect products</p>
                <p class="text-primary font-weight-bold">$50</p>
              </div>
            </div>
          </div>
          <div class="item">
            <div class="block-4 text-center">
              <figure class="block-4-image">
                <img src="{% static 'images/shoe_1.jpg' %}" alt="Image placeholder" class="img-fluid">
              </figure>
              <div class="block-4-text p-4">
                <h3><a href="#">Corater</a></h3>
                <p class="mb-0">Finding perfect products</p>
                <p class="text-primary font-weight-bold">$50</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="site-section block-8">
  <div class="container">
    <div class="row justify-content-center  mb-5">
      <div class="col-md-7 site-section-heading text-center pt-4">
        <h2>Big Sale!</h2>
      </div>
    </div>
    <div class="row align-items-center">
      <div class="col-md-12 col-lg-7 mb-5">
        <a href="#"><img src="{% static 'images/blog_1.jpg' %}" alt="Image placeholder" class="img-fluid rounded"></a>
      </div>
      <div class="col-md-12 col-lg-5 text-center pl-md-5">
        <h2><a href="#">50% less in all items</a></h2>
        <p class="post-meta mb-4">By <a href="#">Carl Smith</a> <span class="block-8-sep">&bullet;</span> September 3, 2018</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam iste dolor accusantium facere corporis ipsum animi deleniti fugiat. Ex, veniam?</p>
        <p><a href="#" class="btn btn-primary btn-sm">Shop Now</a></p>
      </div>
    </div>
  </div>
</div>

{% endblock %}

shop/templates/shop/tags/pagination_numbers.html
{% for num in numbers %}
    <li {% if num == active %} class="active" {% endif %}>
        <a href="?page={{num}}">
            {{num}}
        </a>
    </li>
{% endfor %}